version : '3'

services:

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - inception
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    healthcheck:
      test: mysqladmin ping --host=localhost -p${SQL_ROOT_PASSWORD}
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/ccarnot
    env_file: .env
    restart: always
    healthcheck:
      test: netstat -an | grep 9000 > /dev/null; if [ 0 != $$? ]; then exit 1; fi;
        #      test: ["CMD-SHELL", "[ -f /var/www/ccarnot/wordpress/wp-config.php ] || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/ccarnot
    env_file: .env
    restart: always
    healthcheck:
      test: 'curl -kfsSL https://localhost:443/status'
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 5s

  redis:
    container_name: redis
    image: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    networks:
      - inception
        #    depends_on:
        #      - nginx
      #      wordpress:
      #        condition: service_healthy
    ports:
      - "6379:6379"
        #    volumes:
        #      - wordpress:/var/www/ccarnot
    env_file: .env
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

  vsftpd:
    build: ./requirements/bonus/ftp_server
    container_name: ftp
    image: ftp
    volumes:
      - wordpress:/var/www/ccarnot
    ports:
      - "20-21:20-21"
      - "30000-30009:30000-30009"
    env_file:
      - .env
    restart: unless-stopped
    init: true
    networks:
      - inception
    depends_on:
      wordpress:
        condition: service_healthy

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ccarnot/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ccarnot/data/wordpress'

networks:
  inception:
    driver: bridge
    name: inception
